title: Album Trade
description: Offline-first sticker album manager for FIFA World Cup collections.
theme: minima

plugins:

* jekyll-feed

markdown: kramdown

collections_dir: .

defaults:

* scope:
  path: ""
  values:
  layout: default
